// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8UTAftusO-g8ngnmHIwUv-cHODee94Do',
    appId: '1:32093781844:web:7c3b91cfdc5235b8f9d2c1',
    messagingSenderId: '32093781844',
    projectId: 'attend-15d84',
    authDomain: 'attend-15d84.firebaseapp.com',
    storageBucket: 'attend-15d84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWjZfTFk_zEwATYod5fYSSRTUiXPRT0EM',
    appId: '1:32093781844:android:142b581f6aa467def9d2c1',
    messagingSenderId: '32093781844',
    projectId: 'attend-15d84',
    storageBucket: 'attend-15d84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIbSwYxYKpnGIu2AVZcWu7bYs8HM_biXw',
    appId: '1:32093781844:ios:1b490fdba0a29fd2f9d2c1',
    messagingSenderId: '32093781844',
    projectId: 'attend-15d84',
    storageBucket: 'attend-15d84.appspot.com',
    iosBundleId: 'com.example.attend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIbSwYxYKpnGIu2AVZcWu7bYs8HM_biXw',
    appId: '1:32093781844:ios:c45fb3096f3554a5f9d2c1',
    messagingSenderId: '32093781844',
    projectId: 'attend-15d84',
    storageBucket: 'attend-15d84.appspot.com',
    iosBundleId: 'com.example.attend.RunnerTests',
  );
}
